default: &default
  adapter: trilogy
  host: 127.0.0.1
  port: 3307
  database: failover_example

development:
  <<: *default
  username: app
  password: app
  connection_retries: 2
  retry_deadline: 5

admin:
  <<: *default
  username: admin
  password: admin
